# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Daytime.create(weekday: "Monday", time: "06:30")
Daytime.create(weekday: "Monday", time: "08:00")
Daytime.create(weekday: "Monday", time: "09:30")
Daytime.create(weekday: "Monday", time: "11:00")
Daytime.create(weekday: "Monday", time: "12:30")
Daytime.create(weekday: "Monday", time: "14:00")
Daytime.create(weekday: "Monday", time: "15:30")
Daytime.create(weekday: "Monday", time: "17:00")
Daytime.create(weekday: "Monday", time: "18:30")
Daytime.create(weekday: "Tuesday", time: "06:30")
Daytime.create(weekday: "Tuesday", time: "08:00")
Daytime.create(weekday: "Tuesday", time: "09:30")
Daytime.create(weekday: "Tuesday", time: "11:00")
Daytime.create(weekday: "Tuesday", time: "12:30")
Daytime.create(weekday: "Tuesday", time: "14:00")
Daytime.create(weekday: "Tuesday", time: "15:30")
Daytime.create(weekday: "Tuesday", time: "17:00")
Daytime.create(weekday: "Tuesday", time: "18:30")
Daytime.create(weekday: "Wednesday", time: "06:30")
Daytime.create(weekday: "Wednesday", time: "08:00")
Daytime.create(weekday: "Wednesday", time: "09:30")
Daytime.create(weekday: "Wednesday", time: "11:00")
Daytime.create(weekday: "Wednesday", time: "12:30")
Daytime.create(weekday: "Wednesday", time: "14:00")
Daytime.create(weekday: "Wednesday", time: "15:30")
Daytime.create(weekday: "Wednesday", time: "17:00")
Daytime.create(weekday: "Wednesday", time: "18:30")
Daytime.create(weekday: "Thursday", time: "06:30")
Daytime.create(weekday: "Thursday", time: "08:00")
Daytime.create(weekday: "Thursday", time: "09:30")
Daytime.create(weekday: "Thursday", time: "11:00")
Daytime.create(weekday: "Thursday", time: "12:30")
Daytime.create(weekday: "Thursday", time: "14:00")
Daytime.create(weekday: "Thursday", time: "15:30")
Daytime.create(weekday: "Thursday", time: "17:00")
Daytime.create(weekday: "Thursday", time: "18:30")
Daytime.create(weekday: "Friday", time: "06:30")
Daytime.create(weekday: "Friday", time: "08:00")
Daytime.create(weekday: "Friday", time: "09:30")
Daytime.create(weekday: "Friday", time: "11:00")
Daytime.create(weekday: "Friday", time: "12:30")
Daytime.create(weekday: "Friday", time: "14:00")
Daytime.create(weekday: "Friday", time: "15:30")
Daytime.create(weekday: "Friday", time: "17:00")
Daytime.create(weekday: "Friday", time: "18:30")
Daytime.create(weekday: "Saturday", time: "06:30")
Daytime.create(weekday: "Saturday", time: "08:00")
Daytime.create(weekday: "Saturday", time: "09:30")
Daytime.create(weekday: "Saturday", time: "11:00")
Daytime.create(weekday: "Saturday", time: "12:30")
Daytime.create(weekday: "Saturday", time: "14:00")
Daytime.create(weekday: "Saturday", time: "15:30")
Daytime.create(weekday: "Saturday", time: "17:00")
Daytime.create(weekday: "Saturday", time: "18:30")
Daytime.create(weekday: "Sunday", time: "06:30")
Daytime.create(weekday: "Sunday", time: "08:00")
Daytime.create(weekday: "Sunday", time: "09:30")
Daytime.create(weekday: "Sunday", time: "11:00")
Daytime.create(weekday: "Sunday", time: "12:30")
Daytime.create(weekday: "Sunday", time: "14:00")
Daytime.create(weekday: "Sunday", time: "15:30")
Daytime.create(weekday: "Sunday", time: "17:00")
Daytime.create(weekday: "Sunday", time: "18:30")